{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "#import rhinoscriptsyntax as rs\n",
    "\n",
    "\n",
    "listtest = [6500,6250,6250,6000,6000,5750]\n",
    "extrusions_list = []\n",
    "surfaces_list = []\n",
    "count = 0\n",
    "\n",
    "\n",
    "for i in listtest:\n",
    "    count = count + 1\n",
    "  \n",
    "    # the i is the geometry\n",
    "    # this is where we need to evaluate the line (i) coming in AT ANY POINT and find the z point \n",
    "    #rs.evaluatecurve(i)\n",
    "    current_height = i\n",
    "    \n",
    "    # want to look at both the points and the line\n",
    "    \n",
    "    # the first step so dont do a comparision yet\n",
    "    if count == 1:\n",
    "        previous_height = current_height\n",
    "        previous_line = i\n",
    "        print ('first step at height ' + str(current_height))\n",
    "    else:\n",
    "        # same height levels\n",
    "        if current_height == previous_height:\n",
    "            \n",
    "            print ('surface made')\n",
    "            # we need to do rs.evaluatecurve and draw the two lines\n",
    "            \n",
    "            # this two lines are i and previous line\n",
    "            \n",
    "            #rs. addline(input the two curve types)\n",
    "            #joined_curve = rs.JoinCurves(objs)\n",
    "            #surface = rs.AddPlanarSrf(joined_curve)\n",
    "            #join the previous line with i, evaluate the end points and draw lines between them on both ends and join\n",
    "            # then make a surface\n",
    "            # append it to a surfaces list\n",
    "            # surfaces_list.append[surface]\n",
    "            \n",
    "            \n",
    "            previous_height = current_height\n",
    "            previous_line = i\n",
    "            # this is then where we make our joined polyline\n",
    "            \n",
    "        # if the heights are different \n",
    "        else: \n",
    "            difference = previous_height - current_height\n",
    "            print (difference)\n",
    "            #extrusion = rs.ExtrudeCurveStraight(i, (0,0,difference), (0, 0, difference) )\n",
    "            \n",
    "            #we want to extrude the current i geometry up this height\n",
    "            # extrude i in the y direction by the difference height\n",
    "            # extrusions_list.append[extrusion]\n",
    "            \n",
    "            previous_height = current_height\n",
    "            previous_line = i\n",
    "            \n",
    "            # make sure the last datapoint is a flat\n",
    "            if count == len(listtest):\n",
    "                print ('last data point at height ' + str(current_height))\n",
    "                \n",
    "            \n",
    "\n",
    "            \n",
    "           \n",
    "            \n",
    "            # this is where we want to extrude the difference \n",
    "        #test_difference\n",
    "        \n",
    "\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
